# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
    - id: check-yaml
    - id: destroyed-symlinks
    - id: end-of-file-fixer
    - id: trailing-whitespace

-   repo: local
    hooks:

    - id: sort-imports
      name: sort python imports
      language: system
      entry: poetry run isort
      types: [python]

    - id: format
      name: format python
      language: system
      entry: poetry run black
      types: [python]

    - id: lint
      name: lint
      language: system
      entry: poetry run flake8
      types: [python]

    - id: test
      name: tests
      language: system
      entry: poetry run python -m pytest
      types: [python]
      pass_filenames: false
