name: Run pre-commit

on:
  workflow_call:
    inputs:
      target_path:
        required: false
        type: string
        default: ""
      python_version:
        required: false
        type: string
        default: "3.9"
    secrets: {}

jobs:
    run-pre-commit:
      name: Run pre-commit
      runs-on: ubuntu-latest
      steps:
        - name: Install pre-commit
          run: pipx install pre-commit

        - name: Install poetry
          if: ${{ hashFiles('poetry.lock') != '' }}
          run: pipx install poetry

        - name: Checkout source
          uses: actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref }}

        - uses: actions/setup-python@v3
          with:
            python-version: ${{ inputs.python_version }}
            architecture: x64
            cache: poetry

        - name: Change to target path
          if: ${{ inputs.target_path != '' }}
          run: cd ${{ inputs.target_path }}

        - name: Run pre-commit checks
          run: pre-commit run -a
