name: Run pre-commit

on:
  workflow_call:
    inputs:
      target_path:
        required: false
        type: string
        default: ""
      setup_workflow:
        required: false
        type: string
        default: ""
      python_version:
        required: false
        type: string
        default: "3.8"
    secrets: {}

jobs:
    run-pre-commit:
      name: Run pre-commit
      runs-on: ubuntu-latest
      steps:
        - name: Install pre-commit
          run: pipx install pre-commit

        - name: Checkout source
          uses: actions/checkout@v3
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref }}

        - name: Setup workflow
          if: ${{ inputs.setup_workflow != '' }}
          uses: ${{ inputs.setup_workflow }}
          with:
            python_version: ${{ inputs.python_version }}

        - name: Change to target path
          if: ${{ inputs.target_path != '' }}
          run: cd ${{ inputs.target_path }}

        - name: Run pre-commit checks
          run: pre-commit run -a
