name: Run pre-commit

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
    secrets: {}

jobs:
    run-pre-commit:
      name: Run pre-commit
      runs-on: ubuntu-latest
      steps:

        - uses: actions/setup-python@v3
          with:
            python-version: ${{ inputs.python_version }}
            architecture: x64
            cache: poetry

        - name: Install pre-commit
          run: pipx install --python ${{ inputs.python_version }} poetry
