name: Test run pre-commit

on:
  push: {}

jobs:
    checkout-self:
      name: Checkout self
      runs-on: ubuntu-latest
      steps:
        - name: Checkout local repo
          uses: actions/checkout@v3
          with:
            repository: HRDAG/workflows
            ref: ${{ github.ref }}

    test-run-precommit:
      uses: ./.github/workflows/run-pre-commit.yaml
      with:
        target_path: tests/successful
        setup_workflow: ./.github/workflows/setup-poetry.yaml
      needs: checkout-self
