name: Check makefiles

on:
  push:
    branches: test-workflow

jobs:
    test-check-workflow:
      name: Test check makefile workflow
      runs-on: ubuntu-latest
      uses: HRDAG/workflows/.github/workflows/makefile-check.yaml@test-workflow
