name: Check makefiles

on:
  push: {}

jobs:
    test-check-workflow:
      uses: ${{ env.workflow }}
      env:
        workflow: HRDAG/workflows/.github/workflows/makefile-check.yaml@${{ github.ref }}
